CI: OSX: Fix rpath of libiio + dependencies
analogdevicesinc/libiio pull request #1015
Opened 2023-07-21 11:15 UTC by pcercuei

- Install the dependencies to Library/Frameworks/iio.framework/Versions/Current/Dependencies, and fix the rpath which did not work properly.

- Fix the broken symbolic links in /usr/local/{lib,include}

2023-07-21 17:24 UTC, tfcollins requested changes

2023-07-21 17:24 UTC, tfcollins commented on CI/azure/macos_tar_fixup.sh
> +	name="$(basename ${each})"
Need quotes around ${each}

2023-07-24 06:20 UTC, ccraluca approved these changes

2023-07-25 13:18 UTC, rgetz commented
tested the tar ball - and it seems to work. 

Thanks

2023-07-25 13:18 UTC, rgetz approved these changes

2023-07-25 13:33 UTC, merged