Rename "tests" to "utils" + remove deprecated parameters
analogdevicesinc/libiio pull request #1039
Opened 2023-08-24 15:53 UTC by pcercuei

Move the whole "tests" folder to now be called "utils".

Remove the "-n", "-x" and "-s" parameters of those utility programs.

2023-08-25 21:27 UTC, tfcollins commented on README_BUILD.md
> +`WITH_UTILS`           |  ON |        All | Build the utilitary programs (iio-utils)           |
Should be utility not utilitary

2023-08-25 21:30 UTC, tfcollins requested changes
Remove the doc for the x case as well https://github.com/analogdevicesinc/libiio/blob/f4e6df15f86c49ed265db47f471252f35d215d7e/utils/iio_common.c#L195

2023-08-26 04:13 UTC, rgetz commented
https://github.com/analogdevicesinc/libiio/blob/main/tests/iio_common.h#L50 needs update as well.

2023-08-28 12:36 UTC, rgetz commented
looks good to me. Thanks

2023-09-12 22:16 UTC, tfcollins approved these changes
I think you got everything. Merge please :)

2023-09-13 08:03 UTC, merged