iiod: Make sure network is alive before poking avahi
analogdevicesinc/libiio pull request #1080
Opened 2023-10-29 23:38 UTC by rgetz

In the past, we were only checking hostname, as a way to see if the network was ready, but unfortantely - that doesn't work. The kernel really only needs to have a hostname set for uname() to work, which is what glibc and uclibc actaully do in gethostname().

So - now we actualyl check there is a working, configured ethernet card, that supports mdns (ie multicast) that is up before moving on to making sure there is a hostname.

We also don't allow "none" or "(none)" to be the hostname until after things time out (3 min).

This fixes #1072 and turns:
192.168.2.1:5353 : answer _iio._tcp.local. PTR "iiod on (none)._iio._tcp.local." rclass 0x1 ttl 10 length 17 into:
192.168.2.1:5353 : answer _iio._tcp.local. PTR "iiod on pluto._iio._tcp.local." rclass 0x1 ttl 10 length 16

2023-10-29 23:39 UTC, rgetz commented
Since this fixes a problem on Pluto/M2k - I assume it should be applied to the 0.25 branch, and so that when Michael makes new firmware images - it gets picked up...

-Robin

2023-10-30 06:34 UTC, mhennerich commented
> Since this fixes a problem on Pluto/M2k - I assume it should be applied to the 0.25 branch, and so that when Michael makes new firmware images - it gets picked up...

Let's apply such fixes also to the https://github.com/analogdevicesinc/libiio/tree/libiio-v0 branch.
I can point buildroot there and it'll get included in the next FW release.

2023-10-30 11:48 UTC, pcercuei requested changes
Just some tiny comments, looks OK otherwise.

2023-10-30 11:48 UTC, pcercuei commented on iiod/dns-sd.c
> +		/* If it hasn't started in 20 times over 210 secondsi (3.5 min),
`secondsi` -> `seconds`

2023-10-30 11:48 UTC, pcercuei commented on iiod/dns-sd.c
> +				if (!(ifa->ifa_flags & IFF_UP) )
There's an extra space before the closing parenthesis.

2023-10-30 11:48 UTC, pcercuei commented on iiod/dns-sd.c
> +		struct ifaddrs* ifa = 0;
```c
struct ifaddrs *ifaddr = 0;
struct ifaddrs *ifa = 0;
```

2023-11-10 16:20 UTC, rgetz commented
The CI failure is fixed with this:  https://github.com/analogdevicesinc/libiio/pull/1081/commits/2d92d147985613eb3bc9fc6bc880ea7efbb69015

and has nothing to do with this patch.

2023-11-10 16:24 UTC, rgetz commented
fixed issue pointed out by Codacy

2023-11-10 16:24 UTC, pcercuei commented
Yeah don't worry. I don't require all CIs to succeed to merge a PR, when the errors are obviously unrelated.

2023-11-10 16:24 UTC, pcercuei commented on iiod/dns-sd.c
> +		if (ret || !host[0] || (ts.tv_sec < TIMEOUT && (!strcmp(host, "none") || !strcmp(host, "(none)"))))
I didn't take out my meter but this line looks long, could you break it?

2023-11-13 11:52 UTC, pcercuei approved these changes

2023-11-13 11:52 UTC, merged